project:
  type: website
  output-dir: docs

website:
  title: "Benjamin Black"
  search: TRUE #add search bar
  twitter-card:
    card-style: "summary_large_image"
    creator: "@Blen_Back"
    site: "@Blen_Back"
  open-graph: true
  google-analytics:
    tracking-id: "G-9CCC34ZV10"
    anonymize-ip: true
  page-footer:
    left: |
      {{< fa regular copyright >}} Benjamin Black, 2022<br>
      All content licensed under {{< fa brands creative-commons >}}
      {{< fa brands creative-commons-by >}} {{< fa brands creative-commons-sa >}} {{< fa brands creative-commons-nc >}} [(CC BY-NC-SA 4.0)](http://creativecommons.org/licenses/by-nc-sa/4.0/)
    right: |
      Made with {{< fa brands r-project >}} and [Quarto](https://quarto.org/)<br>
  navbar:
    #logo: logo.jpg
    #title: false
    left:
      - href: index.qmd
        text: Home
        aria-label: "Home"
      - href: about.qmd
        aria-label: "About"
      - href: publications.qmd
        aria-label: "Publications"
      - href: presentations.qmd
        aria-label: "Presentations"
      - href: posts.qmd
        aria-label: "Posts"
      - text: CV
        href: media/Benjamin_black_CV.pdf
        aria-label: "CV"
    right: 
      - text: "{{< fa solid envelope >}}"
        href: mailto:bblack@ethz.ch
        aria-label: "Email"
      - text: "{{< fa brands github >}}"
        href: https://github.com/blenback
        aria-label: "Github"
      - text: "{{< fa brands twitter >}}"
        href: https://twitter.com/Blen_Back
        aria-label: "Twitter"
  

format:
  html:
    theme: sandstone
    mainfont: Lato light
    margin-left: 0.5em
    css: styles.css
    toc: true
    max-width: 1800px

editor: visual

