---
title: "Publications"
page-layout: full
title-block-banner: false
feed: true
format: 
  html: 
    css: css/publications.css
---

<br><h3 style="margin:0!important;padding:0!important;text-decoration:none;">Journal Articles</h3>

\
Wicki, S., **Black, B**., Kurmann, M., Grêt-Regamey, A., 2023. Archetypes of social-ecological-technological systems for managing ecological infrastructure. *Environ. Res. Lett.* 19, 014038. [doi.org/10.1088/1748-9326/ad1080](https://doi.org/10.1088/1748-9326/ad1080)

<a href=media/Archetypes.bib class="btn btn-outline-dark btn-sm" aria-pressed="true" role="button" download=Archetypes.bib> {{< fa solid quotes >}} Cite </a>
<br>

**\
Black, B**., Strien, M.J. van, Adde, A., Grêt-Regamey, A., 2023. Re-considering the status quo: Improving calibration of land use change models through validation of transition potential predictions. *Environmental Modelling & Software* 159, 105574. [doi.org/10.1016/j.envsoft.2022.105574](https://doi.org/10.1016/j.envsoft.2022.105574)

<a href="https://dx.doi.org/10.2139/ssrn.4219023" class="btn btn-outline-dark btn-sm" aria-pressed="true" role="button"> {{< fa solid fingerprint >}} Preprint </a> <a href="https://zenodo.org/record/6912914#.Y7V4mZDYo2w" class="btn btn-outline-dark btn-sm" aria-pressed="true" role="button"> {{< fa solid code >}} Data/Code </a> <a href=media/ICoLCM.bib class="btn btn-outline-dark btn-sm" aria-pressed="true" role="button" download=ICoLCM.bib> {{< fa solid quotes >}} Cite </a>
<br>

**\
Black, B**., Anthony, B.P., 2022. Counterfactual assessment of protected area avoided deforestation in Cambodia: Trends in effectiveness, spillover effects and the influence of establishment date. *Global Ecology and Conservation* 38, e02228. [doi.org/10.1016/j.gecco.2022.e02228](https://doi.org/10.1016/j.gecco.2022.e02228)

<a href="https://zenodo.org/record/6554206#.Y7V79ZDYo2w" class="btn btn-outline-dark btn-sm" aria-pressed="true" role="button"> {{< fa solid code >}} Data/Code </a> <a href=media/Cam_PA_effect.bib class="btn btn-outline-dark btn-sm" aria-pressed="true" role="button" download= Cam_PA_effect.bib> {{< fa solid quotes >}} Cite </a>

<br>

------------------------------------------------------------------------

<br><h3 style="margin:0!important;padding:0!important;text-decoration:none;">Theses</h3>

**\
Black, B**., 2020. Assessing the ecological effectiveness of protected areas in Cambodia: a quasi-experimental counterfactual estimation of avoided deforestation. Central European University, Budapest. [doi.org/10.13140/RG.2.2.28621.10727](http://dx.doi.org/10.13140/RG.2.2.28621.10727)

<a href=media/MSc_thesis.bib class="btn btn-outline-dark btn-sm" aria-pressed="true" role="button" download= MSc_thesis.bib.bib> {{< fa solid quotes >}} Cite </a>
<br>

**\
Black, B**., 2014. Simulating the future potential of degraded Mangrove plots using field data from Kenya. Bachelors thesis. Edinburgh Napier University.[doi.org/10.13140/RG.2.2.20232.49923](https://doi.org/10.13140/RG.2.2.20232.49923)

<a href=media/BSc_thesis.bib class="btn btn-outline-dark btn-sm" aria-pressed="true" role="button" download= BSc_thesis.bib.bib> {{< fa solid quotes >}} Cite </a>


