---
title: "New research project: NASCENT-Peru"
date: "2023-11-30"
image: assets/announcement.svg
image-alt: Logo for NASCENT-Peru project
categories: [Future landscape scenarios, Ecosystem Services, Biodiversity, Peru, SwissRE, Project, NASCENT-Peru]
---

I am excited to be able to introduce a new research project that I will be working on for the next two years: NASCENT-Peru.

The name of the project took some consideration and comes from the acronym: **NA**ture-positive **SC**enarios for **EN**vironmental **T**ransitions in Peru. Of course, also drawing upon the definition of nascent in terms of something begin to grow or change.

This is the first project for which I wrote the proposal and it was funded through the Biodiversity and Ecosystem services scenario modelling challenge put together by [SwissRE](SwissRE.com). I will work on this project until 2025, continuing in the chair of Planning of Landscape and Urban Systems under Prof. Dr. Adrienne Gret-Regamy at ETH Zurich.

We have already put together a multi-lingual [website](https://nascent-peru.github.io/) for the project where we hope to communicate the process and results of the research to a more diverse audience than just through journal articles. To this end we have also created [LinkedIn](https://www.linkedin.com/company/nascent-peru) and [Facebook](https://www.facebook.com/profile.php?id=61557948733975) pages to help spread the word so please follow them if you use these platforms!
